title:        Rails-i8n.org
tagline:      'Interviews, Inspiration, And Tools For The Rails I18n Community'
description:  'An open-source project to capture the spirit and challenges of the Rails internationalization world.'
url:          http://rails-i18n.org
version:      1.0
author:
  name:       'Erez Zukerman'
  email:      'bulk@ezuk.org'
markdown:     rdiscount
permalink:    pretty
highlighter:  pygments
baseurl:      /rails-i18n.org